# Generated by Django 5.0.6 on 2024-07-21 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_text',
            new_name='news_text',
        ),
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 10, 58, 28, 576198, tzinfo=datetime.timezone.utc)),
        ),
    ]
