# Generated by Django 5.0.6 on 2024-12-22 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_rename_new_text_news_news_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_tags',
        ),
        migrations.AddField(
            model_name='news',
            name='news_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 10, 38, 13, 653046, tzinfo=datetime.timezone.utc)),
        ),
    ]
